### ISSUE TITLE
[Forge 1.20.1] Is this a bug?

### ISSUE THREAD

**Issue by DankestO** [yurisuika/Compost#10]
In the mod description it says that it can only be installed on the server and is not necessary on the client, right?

Curiously, when I enter my server it does not let me in, precisely because it tells me that I need the Compost mod. Is it my fault?

> Missing registry data for impl connection:
> 	minecraft:block_entity_type: compost:composter

[latest.log](https://github.com/user-attachments/files/16589898/latest.log)

**Comment by yurisuika** [comment]
https://github.com/yurisuika/Compost/blob/Forge-1.20.1/src/main/resources/META-INF/mods.toml

No, it needs to be installed on both. It looks correct to me though?

**Comment by yurisuika** [comment]
Huh well I see on Modrinth for some reason it said client was unsupported, but that has never been the case. Optionally you used to be able to run it on the client just to change the composter texture and then after that for some client mod support, but for almost a year now it has been mandatory since the block and block entity were added. Maybe I accidentally changed it from `optional` to `unsupported` instead of `required` when that happened. But that should be proper now.

**Comment by DankestO** [comment]
I see, I was saying this because of the part of the description that says:

> While Compost can be ran only server-side, you may want to run it on your client as well for its [Roughly Enough Items](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) integration!

That's why I thought it would be just server side, thank you for the clarification! :D

**Comment by yurisuika** [comment]
Ah, I will remove that, that hasn't been the case since 1.3.x was launched. Thanks!
